import { useCallback, useMemo, useState } from "react";
import {
  BookOpen,
  ClipboardCopy,
  Download,
  FileJson,
  FileText,
  Github,
  RotateCcw,
  ShieldCheck,
  Sparkles,
  Terminal,
  Trash2,
  Wand2,
} from "lucide-react";
import { Button } from "@/components/Button";
import { CopyButton } from "@/components/CopyButton";
import { DownloadButton } from "@/components/DownloadButton";
import { siteMeta } from "@/config/siteMeta";
import { usePersistentState } from "@/hooks/usePersistentState";
import { messages, type Language } from "@/i18n/messages";

export type PrivacyModel = "local-first" | "no-upload" | "no-backend";
export type DeployTarget = "github-pages" | "netlify" | "vercel" | "other";
export type TextLang = "zh" | "en" | "bilingual";
export type LsNeed = "none" | "optional" | "required";
export type ImportExportNeed = "none" | "json" | "file" | "both";
export type ShareNeed = "none" | "optional" | "required";
export type PwaNeed = "none" | "basic" | "recommended";
export type ProjectLevel = "C" | "B" | "A";

export interface WizardFormState {
  projectName: string;
  repoSlug: string;
  level: ProjectLevel;
  description: string;
  targetUser: string;
  corePain: string;
  coreFeatures: string;
  notDoing: string;
  privacyModel: PrivacyModel[];
  deployTarget: DeployTarget;
  textLang: TextLang;
  lsNeed: LsNeed;
  importExportNeed: ImportExportNeed;
  shareNeed: ShareNeed;
  pwaNeed: PwaNeed;
}

const STORAGE_KEY = `${siteMeta.localStoragePrefix}.wizard`;

const DEFAULT_STATE: WizardFormState = {
  projectName: "",
  repoSlug: "",
  level: "C",
  description: "",
  targetUser: "",
  corePain: "",
  coreFeatures: "",
  notDoing: "",
  privacyModel: ["local-first", "no-upload", "no-backend"],
  deployTarget: "github-pages",
  textLang: "bilingual",
  lsNeed: "none",
  importExportNeed: "none",
  shareNeed: "none",
  pwaNeed: "none",
};

const SAMPLE_STATE: WizardFormState = {
  projectName: "JSON Formatter",
  repoSlug: "json-formatter",
  level: "B",
  description: "A browser-based JSON formatter, validator, and minifier with syntax highlighting.",
  targetUser: "Developers and API testers who work with JSON daily.",
  corePain: "Online JSON tools are slow, full of ads, and upload your data to servers.",
  coreFeatures: "Format and pretty-print JSON\nMinify JSON\nValidate with error line numbers\nSyntax highlighting\nCopy formatted result\nDownload as .json file",
  notDoing: "No server-side processing\nNo file upload to backend\nNo user accounts\nNo collaborative editing\nNo schema generation",
  privacyModel: ["local-first", "no-upload", "no-backend"],
  deployTarget: "github-pages",
  textLang: "bilingual",
  lsNeed: "optional",
  importExportNeed: "json",
  shareNeed: "optional",
  pwaNeed: "basic",
};

function isKebabCase(s: string): boolean {
  return /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(s);
}

function toKebabCase(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function generateProjectSpec(state: WizardFormState, lang: Language): string {
  const lines: string[] = [];
  const t = lang === "zh" ? "中文" : "English";

  lines.push(`# PROJECT_SPEC: ${state.projectName || "(unnamed)"}`);
  lines.push("");
  lines.push(`Generated by Open Tools Starter Wizard v${siteMeta.version}`);
  lines.push(`Language: ${t}`);
  lines.push("");

  lines.push("## Project Identity");
  lines.push(`- **Name**: ${state.projectName || "(unnamed)"}`);
  lines.push(`- **Repo slug**: ${state.repoSlug || "(not set)"}`);
  lines.push(`- **Level**: ${state.level}`);
  lines.push(`- **Description**: ${state.description || "(not set)"}`);
  lines.push("");

  lines.push("## Target & Problem");
  lines.push(`- **Target user**: ${state.targetUser || "(not set)"}`);
  lines.push(`- **Core pain point**: ${state.corePain || "(not set)"}`);
  lines.push("");

  lines.push("## Core Features");
  lines.push(state.coreFeatures || "(not set)");
  lines.push("");

  lines.push("## Explicit Non-Goals");
  lines.push(state.notDoing || "(not set)");
  lines.push("");

  lines.push("## Technical Decisions");
  lines.push(`- **Privacy model**: ${state.privacyModel.join(", ")}`);
  lines.push(`- **Deploy target**: ${state.deployTarget}`);
  lines.push(`- **Text language**: ${state.textLang}`);
  lines.push(`- **localStorage**: ${state.lsNeed}`);
  lines.push(`- **Import/Export**: ${state.importExportNeed}`);
  lines.push(`- **Share links**: ${state.shareNeed}`);
  lines.push(`- **PWA**: ${state.pwaNeed}`);
  lines.push("");

  lines.push("## Level Requirements");
  if (state.level === "C") {
    lines.push("- Modern UI, mobile layout, dark mode");
    lines.push("- Chinese/English copy, sample data");
    lines.push("- One-click copy, README");
    lines.push("- GitHub Pages deployment");
  } else if (state.level === "B") {
    lines.push("- All Level C requirements");
    lines.push("- localStorage persistence");
    lines.push("- JSON import/export");
    lines.push("- Result file downloads");
    lines.push("- Share links");
    lines.push("- Error feedback");
    lines.push("- self-test, release notes, privacy note");
  } else {
    lines.push("- All Level B requirements");
    lines.push("- PWA with offline support");
    lines.push("- Batch processing");
    lines.push("- Modular tool architecture");
    lines.push("- Shared component library");
    lines.push("- Settings center");
    lines.push("- Health checks, preflight");
    lines.push("- SEO/OpenGraph");
  }
  lines.push("");

  return lines.join("\n");
}

function generateOpenCodePrompt(state: WizardFormState, lang: Language): string {
  const lines: string[] = [];

  lines.push(`# OpenCode Prompt: ${state.projectName || "(unnamed)"}`);
  lines.push("");
  lines.push(`Create a Level ${state.level} pure frontend tool based on open-tools-starter.`);
  lines.push("");

  if (state.projectName) lines.push(`**Project**: ${state.projectName}`);
  if (state.description) lines.push(`**Description**: ${state.description}`);
  if (state.targetUser) lines.push(`**Target user**: ${state.targetUser}`);
  if (state.corePain) lines.push(`**Core problem**: ${state.corePain}`);
  lines.push("");

  lines.push("## Core Features");
  lines.push(state.coreFeatures || "(define your features here)");
  lines.push("");

  lines.push("## Non-Goals");
  lines.push(state.notDoing || "(define what NOT to build)");
  lines.push("");

  lines.push("## Technical Constraints");
  lines.push(`- Level ${state.level} project`);
  lines.push(`- Privacy: ${state.privacyModel.join(", ")}`);
  lines.push(`- Deploy: ${state.deployTarget}`);
  lines.push(`- Language: ${state.textLang}`);
  lines.push(`- localStorage: ${state.lsNeed}`);
  lines.push(`- Import/Export: ${state.importExportNeed}`);
  lines.push(`- Share links: ${state.shareNeed}`);
  lines.push(`- PWA: ${state.pwaNeed}`);
  lines.push("");

  lines.push("## Requirements");
  lines.push("- Vite + React + TypeScript");
  lines.push("- GitHub Pages Ready");
  lines.push("- Mobile layout, dark mode");
  lines.push("- No backend, no login, no file upload");
  lines.push("- All data in browser localStorage");
  lines.push("- All buttons must be functional");
  lines.push("");

  lines.push(`Language preference: ${lang === "zh" ? "Chinese" : "English"} documentation and UI copy.`);
  lines.push("");

  return lines.join("\n");
}

function generateCreateCommand(state: WizardFormState): string {
  const parts = ["npm run create:project --"];
  if (state.repoSlug) parts.push(`--name ${state.repoSlug}`);
  if (state.projectName) parts.push(`--title "${state.projectName}"`);
  parts.push(`--level ${state.level}`);
  if (state.description) parts.push(`--description "${state.description}"`);
  parts.push("--dry-run");
  return parts.join(" ");
}

function generateReadmeDraft(state: WizardFormState): string {
  const lines: string[] = [];
  lines.push(`# ${state.projectName || "(unnamed)"}`);
  lines.push("");
  if (state.description) lines.push(state.description);
  lines.push("");
  lines.push("## Features");
  if (state.coreFeatures) {
    for (const f of state.coreFeatures.split("\n").filter(Boolean)) {
      lines.push(`- ${f.trim()}`);
    }
  }
  lines.push("");
  lines.push("## Privacy");
  lines.push(`- ${state.privacyModel.join("\n- ")}`);
  lines.push("");
  lines.push("## Getting Started");
  lines.push("```bash");
  lines.push("npm install");
  lines.push("npm run dev");
  lines.push("```");
  lines.push("");
  lines.push("## Deployment");
  lines.push(`Target: ${state.deployTarget}`);
  lines.push("");
  return lines.join("\n");
}

function generateChecklist(state: WizardFormState): string {
  const lines: string[] = [];
  lines.push(`# Release Checklist: ${state.projectName || "(unnamed)"}`);
  lines.push("");
  lines.push("- [ ] All buttons functional");
  lines.push("- [ ] Mobile layout works");
  lines.push("- [ ] Dark mode readable");
  lines.push("- [ ] i18n complete");
  lines.push("- [ ] README updated");
  lines.push("- [ ] RELEASE_NOTES updated");
  lines.push("- [ ] Version consistent (package.json, siteMeta, sw.js, manifest)");
  lines.push("- [ ] No placeholder markers remaining");
  lines.push("- [ ] `npm run build` passes");
  lines.push("- [ ] `npm run self-test` passes");
  lines.push("- [ ] `npm run preflight` passes");
  if (state.lsNeed !== "none") lines.push("- [ ] localStorage persistence works");
  if (state.importExportNeed !== "none") lines.push("- [ ] Import/export works");
  if (state.shareNeed !== "none") lines.push("- [ ] Share links work");
  if (state.pwaNeed !== "none") lines.push("- [ ] PWA installs and caches");
  lines.push("");
  return lines.join("\n");
}

function generateSpecJson(state: WizardFormState): string {
  return JSON.stringify(
    {
      name: state.repoSlug || "my-tool",
      title: state.projectName || "My Tool",
      level: state.level,
      description: state.description,
      targetUser: state.targetUser,
      corePain: state.corePain,
      coreFeatures: state.coreFeatures.split("\n").filter(Boolean),
      notDoing: state.notDoing.split("\n").filter(Boolean),
      privacy: state.privacyModel,
      deploy: state.deployTarget,
      language: state.textLang,
      localStorage: state.lsNeed,
      importExport: state.importExportNeed,
      shareLinks: state.shareNeed,
      pwa: state.pwaNeed,
      generatedAt: new Date().toISOString(),
      generatorVersion: siteMeta.version,
    },
    null,
    2,
  );
}

function generateRepoSetup(state: WizardFormState): string {
  const lines: string[] = [];
  lines.push(`# GitHub Repository Setup: ${state.projectName || "(unnamed)"}`);
  lines.push("");
  lines.push("## Repository Description");
  lines.push(state.description || "(one-line description)");
  lines.push("");
  lines.push("## Website URL");
  lines.push(`https://w0nderful666.github.io/${state.repoSlug || "repo"}/`);
  lines.push("");
  lines.push("## Topics");
  const topics: string[] = [
    state.repoSlug || "repo",
    "github-pages",
    "frontend",
    "local-first",
    "no-backend",
    "privacy-friendly",
    "vite",
    "react",
    "typescript",
  ];
  if (state.level === "A") topics.push("pwa", "offline-ready");
  for (const m of state.privacyModel) {
    topics.push(m.replace("-", ""));
  }
  lines.push(topics.join(", "));
  lines.push("");
  lines.push("## About");
  lines.push(`- Description: ${state.description || "(not set)"}`);
  lines.push(`- Website: https://w0nderful666.github.io/${state.repoSlug || "repo"}/`);
  lines.push("- Topics: (see above)");
  lines.push("");
  return lines.join("\n");
}

function generateReleaseDraft(state: WizardFormState): string {
  const lines: string[] = [];
  lines.push("# v0.1.0 - Initial Release");
  lines.push("");
  if (state.description) lines.push(state.description);
  lines.push("");
  lines.push("## Highlights");
  if (state.coreFeatures) {
    for (const f of state.coreFeatures.split("\n").filter(Boolean)) {
      lines.push(`- ${f.trim()}`);
    }
  } else {
    lines.push("(features)");
  }
  lines.push("");
  lines.push("## Technical");
  lines.push("- Built with Vite + React + TypeScript");
  lines.push("- Deployed to GitHub Pages");
  lines.push(`- Privacy: ${state.privacyModel.join(", ")}`);
  lines.push(`- Level: ${state.level}`);
  lines.push("");
  lines.push("## Verification");
  lines.push("```bash");
  lines.push("npm install");
  lines.push("npm run build");
  lines.push("npm run self-test");
  lines.push("npm run preflight");
  lines.push("```");
  lines.push("");
  lines.push("## Links");
  lines.push(`- Live Demo: https://w0nderful666.github.io/${state.repoSlug || "repo"}/`);
  lines.push(`- Repository: https://github.com/w0nderful666/${state.repoSlug || "repo"}`);
  lines.push("");
  return lines.join("\n");
}

function generateRoadmapIssues(state: WizardFormState): string {
  const lines: string[] = [];
  lines.push(`# Roadmap Issues: ${state.projectName || "(unnamed)"}`);
  lines.push("");
  lines.push("## Issue 1: Initial Setup");
  lines.push('Title: "chore: initial project setup from open-tools-starter"');
  lines.push("Labels: chore, setup");
  lines.push("Description:");
  lines.push("- [ ] Copy template to new repo");
  lines.push("- [ ] Update siteMeta.ts");
  lines.push("- [ ] Update package.json");
  lines.push("- [ ] Update README.md");
  lines.push("- [ ] Configure GitHub Pages");
  lines.push("- [ ] Run npm run test:all");
  lines.push("- [ ] Verify GitHub Actions workflow");
  lines.push("");
  lines.push("## Issue 2: Core Feature Implementation");
  lines.push('Title: "feat: implement core functionality"');
  lines.push("Labels: feature, priority: high");
  lines.push("Description:");
  lines.push("Core features to implement:");
  if (state.coreFeatures) {
    for (const f of state.coreFeatures.split("\n").filter(Boolean)) {
      lines.push(`- [ ] ${f.trim()}`);
    }
  } else {
    lines.push("(define features)");
  }
  lines.push("");
  lines.push("## Issue 3: Quality Gate");
  lines.push('Title: "chore: pass all quality gates"');
  lines.push("Labels: chore, quality");
  lines.push("Description:");
  lines.push("- [ ] npm run build passes");
  lines.push("- [ ] npm run self-test passes");
  lines.push("- [ ] npm run preflight passes");
  lines.push("- [ ] npm run test:all passes");
  lines.push("- [ ] Mobile layout verified");
  lines.push("- [ ] Dark mode verified");
  lines.push("- [ ] i18n complete");
  lines.push("");
  return lines.join("\n");
}

function generateScreenshotReminder(state: WizardFormState): string {
  const lines: string[] = [];
  lines.push(`# README Screenshot Guide: ${state.projectName || "(unnamed)"}`);
  lines.push("");
  lines.push("## Required Screenshots");
  lines.push("");
  lines.push("Add these screenshots to your README:");
  lines.push("");
  lines.push("1. **Hero screenshot** - Desktop view of the main page");
  lines.push("   - Path: docs/assets/screenshot-desktop.png");
  lines.push("   - Width: 1200px recommended");
  lines.push("");
  lines.push("2. **Mobile screenshot** - Mobile view");
  lines.push("   - Path: docs/assets/screenshot-mobile.png");
  lines.push("   - Width: 375px recommended");
  lines.push("");
  lines.push("3. **Dark mode screenshot** (optional)");
  lines.push("   - Path: docs/assets/screenshot-dark.png");
  lines.push("");
  lines.push("## How to Capture");
  lines.push("");
  lines.push("1. Run npm run dev");
  lines.push("2. Open in browser");
  lines.push("3. Take screenshots at different viewport sizes");
  lines.push("4. Save to docs/assets/");
  lines.push("5. Reference in README:");
  lines.push("");
  lines.push("```markdown");
  lines.push("![Desktop](docs/assets/screenshot-desktop.png)");
  lines.push("![Mobile](docs/assets/screenshot-mobile.png)");
  lines.push("```");
  lines.push("");
  lines.push("## OG Image");
  lines.push("");
  lines.push("The template includes public/og-image.svg. Replace it with a project-specific version.");
  lines.push("");
  return lines.join("\n");
}

function generateSecuritySummary(state: WizardFormState): string {
  const lines: string[] = [];
  lines.push(`# Security Summary: ${state.projectName || "(unnamed)"}`);
  lines.push("");
  lines.push("## Privacy Model");
  for (const m of state.privacyModel) {
    lines.push(`- ${m}`);
  }
  lines.push("");
  lines.push("## Key Security Properties");
  lines.push("- Pure frontend: no server-side code");
  lines.push("- Local-first: all data stays in browser");
  lines.push("- No authentication: no login system");
  lines.push("- No file upload: user files never leave the device");
  lines.push("- No tracking: no analytics, no external requests");
  lines.push("- Open source: code is auditable");
  lines.push("");
  lines.push("## What Users Should Know");
  lines.push("- All data is stored in browser localStorage");
  lines.push("- Clearing browser data will remove saved settings");
  lines.push("- No data is transmitted to any server");
  lines.push(
    state.pwaNeed !== "none"
      ? "- PWA caches assets locally for offline use"
      : "- No PWA caching",
  );
  lines.push("");
  lines.push("## For Maintainers");
  lines.push("- Never add backend endpoints");
  lines.push("- Never add user authentication");
  lines.push("- Never add file upload functionality");
  lines.push("- Never add analytics or tracking scripts");
  lines.push("- Review all PRs for privacy boundary violations");
  lines.push("");
  return lines.join("\n");
}

function generateContributingSummary(state: WizardFormState): string {
  const lines: string[] = [];
  lines.push(`# Contributing Guide: ${state.projectName || "(unnamed)"}`);
  lines.push("");
  lines.push("## Welcome");
  lines.push(
    `Contributions are welcome! This is a ${state.level}-level local-first frontend tool.`,
  );
  lines.push("");
  lines.push("## How to Contribute");
  lines.push("");
  lines.push("### Report Bugs");
  lines.push("Use the bug report issue template. Include:");
  lines.push("- Steps to reproduce");
  lines.push("- Expected vs actual behavior");
  lines.push("- Browser and device info");
  lines.push("");
  lines.push("### Suggest Features");
  lines.push("Use the feature request issue template. Make sure the suggestion:");
  lines.push("- Fits the Local First / No Backend model");
  lines.push(`- Is appropriate for a Level ${state.level} project`);
  lines.push("");
  lines.push("### Submit Code");
  lines.push("1. Fork the repo");
  lines.push("2. Create a feature branch");
  lines.push("3. Make your changes");
  lines.push("4. Run: npm run test:all");
  lines.push("5. Submit a PR");
  lines.push("");
  lines.push("## Development");
  lines.push("```bash");
  lines.push("npm install");
  lines.push("npm run dev");
  lines.push("```");
  lines.push("");
  lines.push("## Rules");
  lines.push("- No backend code");
  lines.push("- No login systems");
  lines.push("- No file upload to servers");
  lines.push("- No external tracking");
  lines.push("- All buttons must work");
  lines.push("- Mobile layout required");
  lines.push("- Dark mode required");
  lines.push("- i18n (zh/en) required");
  lines.push("");
  return lines.join("\n");
}

type OutputKey =
  | "spec"
  | "prompt"
  | "command"
  | "readme"
  | "checklist"
  | "json"
  | "repo-setup"
  | "release-draft"
  | "roadmap"
  | "screenshots"
  | "security"
  | "contributing";

interface OutputDef {
  key: OutputKey;
  icon: React.ReactNode;
  titleZh: string;
  titleEn: string;
  copyLabel: string;
  downloadLabel: string;
  fileName: string;
  mimeType: string;
}

const OUTPUTS: OutputDef[] = [
  {
    key: "spec",
    icon: <FileText size={16} />,
    titleZh: "PROJECT_SPEC.md",
    titleEn: "PROJECT_SPEC.md",
    copyLabel: "Copy",
    downloadLabel: "Download",
    fileName: "PROJECT_SPEC.md",
    mimeType: "text/markdown",
  },
  {
    key: "prompt",
    icon: <Sparkles size={16} />,
    titleZh: "OpenCode 提示词",
    titleEn: "OpenCode Prompt",
    copyLabel: "Copy",
    downloadLabel: "Download",
    fileName: "opencode-prompt.txt",
    mimeType: "text/plain",
  },
  {
    key: "command",
    icon: <Terminal size={16} />,
    titleZh: "create-project 命令",
    titleEn: "create-project Command",
    copyLabel: "Copy",
    downloadLabel: "Download",
    fileName: "create-command.txt",
    mimeType: "text/plain",
  },
  {
    key: "readme",
    icon: <BookOpen size={16} />,
    titleZh: "README 结构草案",
    titleEn: "README Draft",
    copyLabel: "Copy",
    downloadLabel: "Download",
    fileName: "README-draft.md",
    mimeType: "text/markdown",
  },
  {
    key: "checklist",
    icon: <ClipboardCopy size={16} />,
    titleZh: "发布前检查清单",
    titleEn: "Release Checklist",
    copyLabel: "Copy",
    downloadLabel: "Download",
    fileName: "release-checklist.md",
    mimeType: "text/markdown",
  },
  {
    key: "json",
    icon: <FileJson size={16} />,
    titleZh: "Spec JSON",
    titleEn: "Spec JSON",
    copyLabel: "Copy",
    downloadLabel: "Download",
    fileName: "spec.json",
    mimeType: "application/json",
  },
  {
    key: "repo-setup",
    icon: <Github size={16} />,
    titleZh: "GitHub 仓库设置",
    titleEn: "GitHub Repo Setup",
    copyLabel: "Copy",
    downloadLabel: "Download",
    fileName: "github-repo-setup.md",
    mimeType: "text/markdown",
  },
  {
    key: "release-draft",
    icon: <FileText size={16} />,
    titleZh: "v0.1.0 Release 草案",
    titleEn: "v0.1.0 Release Draft",
    copyLabel: "Copy",
    downloadLabel: "Download",
    fileName: "release-draft-v0.1.0.md",
    mimeType: "text/markdown",
  },
  {
    key: "roadmap",
    icon: <ClipboardCopy size={16} />,
    titleZh: "Roadmap Issues 草案",
    titleEn: "Roadmap Issues Draft",
    copyLabel: "Copy",
    downloadLabel: "Download",
    fileName: "roadmap-issues.md",
    mimeType: "text/markdown",
  },
  {
    key: "screenshots",
    icon: <Sparkles size={16} />,
    titleZh: "README 截图指南",
    titleEn: "README Screenshot Guide",
    copyLabel: "Copy",
    downloadLabel: "Download",
    fileName: "screenshot-guide.md",
    mimeType: "text/markdown",
  },
  {
    key: "security",
    icon: <ShieldCheck size={16} />,
    titleZh: "SECURITY 摘要",
    titleEn: "SECURITY Summary",
    copyLabel: "Copy",
    downloadLabel: "Download",
    fileName: "security-summary.md",
    mimeType: "text/markdown",
  },
  {
    key: "contributing",
    icon: <BookOpen size={16} />,
    titleZh: "CONTRIBUTING 摘要",
    titleEn: "CONTRIBUTING Summary",
    copyLabel: "Copy",
    downloadLabel: "Download",
    fileName: "contributing-summary.md",
    mimeType: "text/markdown",
  },
];

type WizardProps = {
  language: Language;
  showToast: (text: string, tone?: "success" | "danger") => void;
};

export function StarterWizard({ language, showToast }: WizardProps) {
  const [form, setForm] = usePersistentState<WizardFormState>(
    STORAGE_KEY,
    DEFAULT_STATE,
  );
  const [expandedOutput, setExpandedOutput] = useState<OutputKey | null>(null);

  const t = messages[language];

  const update = useCallback(
    <K extends keyof WizardFormState>(key: K, value: WizardFormState[K]) => {
      setForm((prev) => ({ ...prev, [key]: value }));
    },
    [setForm],
  );

  const updateSlug = useCallback(
    (value: string) => {
      setForm((prev: WizardFormState) => ({
        ...prev,
        projectName: value,
        repoSlug: toKebabCase(value),
      }));
    },
    [setForm],
  );

  const updateSlugDirect = useCallback(
    (value: string) => {
      setForm((prev: WizardFormState) => ({ ...prev, repoSlug: value }));
    },
    [setForm],
  );

  const togglePrivacy = useCallback(
    (model: PrivacyModel) => {
      setForm((prev: WizardFormState) => {
        const has = prev.privacyModel.includes(model);
        return {
          ...prev,
          privacyModel: has
            ? prev.privacyModel.filter((m: PrivacyModel) => m !== model)
            : [...prev.privacyModel, model],
        };
      });
    },
    [setForm],
  );

  const resetSample = useCallback(() => {
    setForm(SAMPLE_STATE);
    showToast(language === "zh" ? "已加载示例数据" : "Sample data loaded");
  }, [setForm, showToast, language]);

  const clearForm = useCallback(() => {
    setForm(DEFAULT_STATE);
    showToast(language === "zh" ? "表单已清空" : "Form cleared");
  }, [setForm, showToast, language]);

  const outputs = useMemo(() => {
    const generators: Record<OutputKey, () => string> = {
      spec: () => generateProjectSpec(form, language),
      prompt: () => generateOpenCodePrompt(form, language),
      command: () => generateCreateCommand(form),
      readme: () => generateReadmeDraft(form),
      checklist: () => generateChecklist(form),
      json: () => generateSpecJson(form),
      "repo-setup": () => generateRepoSetup(form),
      "release-draft": () => generateReleaseDraft(form),
      roadmap: () => generateRoadmapIssues(form),
      screenshots: () => generateScreenshotReminder(form),
      security: () => generateSecuritySummary(form),
      contributing: () => generateContributingSummary(form),
    };
    return Object.fromEntries(
      OUTPUTS.map((def) => [def.key, generators[def.key]()]),
    ) as Record<OutputKey, string>;
  }, [form, language]);

  const slugValid = !form.repoSlug || isKebabCase(form.repoSlug);
  const hasContent = form.projectName || form.description || form.coreFeatures;

  return (
    <section className="section wizard" data-testid="starter-wizard" id="wizard">
      <div className="section__header">
        <p className="eyebrow">
          <Wand2 size={14} aria-hidden="true" />{" "}
          {language === "zh" ? "项目启动向导" : "Starter Wizard"}
        </p>
        <h2>{t.wizard.title}</h2>
        <p>{t.wizard.intro}</p>
      </div>

      <div className="wizard__layout">
        {/* Form */}
        <div className="wizard__form" data-testid="wizard-form">
          <div className="wizard__form-actions">
            <Button
              icon={<Sparkles size={16} />}
              onClick={resetSample}
              size="sm"
              variant="ghost"
            >
              {t.wizard.resetSample}
            </Button>
            <Button
              icon={<Trash2 size={16} />}
              onClick={clearForm}
              size="sm"
              variant="ghost"
            >
              {t.wizard.clearForm}
            </Button>
          </div>

          {/* Project Identity */}
          <fieldset className="wizard__fieldset">
            <legend>{t.wizard.sectionIdentity}</legend>
            <label className="wizard__label">
              <span>{t.wizard.projectName}</span>
              <input
                className="wizard__input"
                data-testid="wizard-project-name"
                onChange={(e) => updateSlug(e.target.value)}
                placeholder={language === "zh" ? "如：JSON 格式化工具" : "e.g., JSON Formatter"}
                type="text"
                value={form.projectName}
              />
            </label>
            <label className="wizard__label">
              <span>{t.wizard.repoSlug}</span>
              <input
                className={`wizard__input ${!slugValid ? "wizard__input--error" : ""}`}
                data-testid="wizard-repo-slug"
                onChange={(e) => updateSlugDirect(e.target.value)}
                placeholder="json-formatter"
                type="text"
                value={form.repoSlug}
              />
              {!slugValid && (
                <span className="wizard__error">{t.wizard.slugError}</span>
              )}
            </label>
            <label className="wizard__label">
              <span>{t.wizard.level}</span>
              <div className="wizard__level-btns" data-testid="wizard-level">
                {(["C", "B", "A"] as ProjectLevel[]).map((lv) => (
                  <button
                    className={`wizard__level-btn ${form.level === lv ? "is-active" : ""}`}
                    key={lv}
                    onClick={() => update("level", lv)}
                    type="button"
                  >
                    {lv}
                  </button>
                ))}
              </div>
            </label>
            <label className="wizard__label">
              <span>{t.wizard.description}</span>
              <textarea
                className="wizard__textarea"
                data-testid="wizard-description"
                onChange={(e) => update("description", e.target.value)}
                placeholder={
                  language === "zh"
                    ? "一句话说明这个工具做什么"
                    : "One sentence about what this tool does"
                }
                rows={2}
                value={form.description}
              />
            </label>
          </fieldset>

          {/* Problem & User */}
          <fieldset className="wizard__fieldset">
            <legend>{t.wizard.sectionProblem}</legend>
            <label className="wizard__label">
              <span>{t.wizard.targetUser}</span>
              <input
                className="wizard__input"
                onChange={(e) => update("targetUser", e.target.value)}
                placeholder={language === "zh" ? "谁会用这个工具？" : "Who will use this?"}
                type="text"
                value={form.targetUser}
              />
            </label>
            <label className="wizard__label">
              <span>{t.wizard.corePain}</span>
              <textarea
                className="wizard__textarea"
                onChange={(e) => update("corePain", e.target.value)}
                placeholder={
                  language === "zh"
                    ? "用户现在遇到什么问题？"
                    : "What problem does the user face today?"
                }
                rows={2}
                value={form.corePain}
              />
            </label>
          </fieldset>

          {/* Features */}
          <fieldset className="wizard__fieldset">
            <legend>{t.wizard.sectionFeatures}</legend>
            <label className="wizard__label">
              <span>{t.wizard.coreFeatures}</span>
              <textarea
                className="wizard__textarea wizard__textarea--tall"
                data-testid="wizard-features"
                onChange={(e) => update("coreFeatures", e.target.value)}
                placeholder={
                  language === "zh"
                    ? "每行一个核心功能"
                    : "One core feature per line"
                }
                rows={5}
                value={form.coreFeatures}
              />
            </label>
            <label className="wizard__label">
              <span>{t.wizard.notDoing}</span>
              <textarea
                className="wizard__textarea wizard__textarea--tall"
                data-testid="wizard-not-doing"
                onChange={(e) => update("notDoing", e.target.value)}
                placeholder={
                  language === "zh"
                    ? "每行一个明确不做的事"
                    : "One non-goal per line"
                }
                rows={4}
                value={form.notDoing}
              />
            </label>
          </fieldset>

          {/* Technical Decisions */}
          <fieldset className="wizard__fieldset">
            <legend>{t.wizard.sectionTechnical}</legend>

            <label className="wizard__label">
              <span>{t.wizard.privacyModel}</span>
              <div className="wizard__check-group">
                {(
                  [
                    { key: "local-first", label: "Local First" },
                    { key: "no-upload", label: "No Upload" },
                    { key: "no-backend", label: "No Backend" },
                  ] as const
                ).map((opt) => (
                  <label className="wizard__check" key={opt.key}>
                    <input
                      checked={form.privacyModel.includes(opt.key)}
                      onChange={() => togglePrivacy(opt.key)}
                      type="checkbox"
                    />
                    <span>{opt.label}</span>
                  </label>
                ))}
              </div>
            </label>

            <div className="wizard__row">
              <label className="wizard__label wizard__label--half">
                <span>{t.wizard.deployTarget}</span>
                <select
                  className="wizard__select"
                  onChange={(e) => update("deployTarget", e.target.value as DeployTarget)}
                  value={form.deployTarget}
                >
                  <option value="github-pages">GitHub Pages</option>
                  <option value="netlify">Netlify</option>
                  <option value="vercel">Vercel</option>
                  <option value="other">Other</option>
                </select>
              </label>
              <label className="wizard__label wizard__label--half">
                <span>{t.wizard.textLang}</span>
                <select
                  className="wizard__select"
                  onChange={(e) => update("textLang", e.target.value as TextLang)}
                  value={form.textLang}
                >
                  <option value="zh">{language === "zh" ? "中文" : "Chinese"}</option>
                  <option value="en">English</option>
                  <option value="bilingual">{language === "zh" ? "中英双语" : "Bilingual"}</option>
                </select>
              </label>
            </div>

            <div className="wizard__row">
              <label className="wizard__label wizard__label--half">
                <span>{t.wizard.lsNeed}</span>
                <select
                  className="wizard__select"
                  onChange={(e) => update("lsNeed", e.target.value as LsNeed)}
                  value={form.lsNeed}
                >
                  <option value="none">none</option>
                  <option value="optional">optional</option>
                  <option value="required">required</option>
                </select>
              </label>
              <label className="wizard__label wizard__label--half">
                <span>{t.wizard.importExportNeed}</span>
                <select
                  className="wizard__select"
                  onChange={(e) =>
                    update("importExportNeed", e.target.value as ImportExportNeed)
                  }
                  value={form.importExportNeed}
                >
                  <option value="none">none</option>
                  <option value="json">json</option>
                  <option value="file">file</option>
                  <option value="both">both</option>
                </select>
              </label>
            </div>

            <div className="wizard__row">
              <label className="wizard__label wizard__label--half">
                <span>{t.wizard.shareNeed}</span>
                <select
                  className="wizard__select"
                  onChange={(e) => update("shareNeed", e.target.value as ShareNeed)}
                  value={form.shareNeed}
                >
                  <option value="none">none</option>
                  <option value="optional">optional</option>
                  <option value="required">required</option>
                </select>
              </label>
              <label className="wizard__label wizard__label--half">
                <span>{t.wizard.pwaNeed}</span>
                <select
                  className="wizard__select"
                  onChange={(e) => update("pwaNeed", e.target.value as PwaNeed)}
                  value={form.pwaNeed}
                >
                  <option value="none">none</option>
                  <option value="basic">basic</option>
                  <option value="recommended">recommended</option>
                </select>
              </label>
            </div>
          </fieldset>
        </div>

        {/* Outputs */}
        <div className="wizard__outputs" data-testid="wizard-outputs">
          <h3 className="wizard__outputs-title">
            <Sparkles size={18} aria-hidden="true" />
            {language === "zh" ? "实时生成物" : "Live Outputs"}
          </h3>

          {!hasContent ? (
            <div className="wizard__empty">
              <p>
                {language === "zh"
                  ? "填写左侧表单，生成物将实时出现。"
                  : "Fill in the form on the left. Outputs appear in real time."}
              </p>
            </div>
          ) : (
            <div className="wizard__output-list">
              {OUTPUTS.map((def) => {
                const content = outputs[def.key];
                const isExpanded = expandedOutput === def.key;
                const preview = content.split("\n").slice(0, 4).join("\n");
                return (
                  <div
                    className={`wizard__output-card ${isExpanded ? "is-expanded" : ""}`}
                    data-testid={`wizard-output-${def.key}`}
                    key={def.key}
                  >
                    <button
                      className="wizard__output-header"
                      onClick={() => setExpandedOutput(isExpanded ? null : def.key)}
                      type="button"
                    >
                      {def.icon}
                      <span>{language === "zh" ? def.titleZh : def.titleEn}</span>
                    </button>
                    <pre className="wizard__output-preview">
                      {isExpanded ? content : preview}
                    </pre>
                    <div className="wizard__output-actions">
                      <CopyButton
                        copiedLabel={language === "zh" ? "已复制" : "Copied"}
                        label={language === "zh" ? "复制" : "Copy"}
                        onCopied={() =>
                          showToast(
                            language === "zh"
                              ? `已复制 ${def.titleZh}`
                              : `Copied ${def.titleEn}`,
                          )
                        }
                        onError={() =>
                          showToast(
                            language === "zh" ? "复制失败" : "Copy failed",
                            "danger",
                          )
                        }
                        text={content}
                      />
                      <DownloadButton
                        content={content}
                        fileName={def.fileName}
                        label={language === "zh" ? "下载" : "Download"}
                        mimeType={def.mimeType}
                        onDownloaded={() =>
                          showToast(
                            language === "zh"
                              ? `已下载 ${def.fileName}`
                              : `Downloaded ${def.fileName}`,
                          )
                        }
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
